### ISSUE TITLE
Adding Random no Generator to Papilio One 500k

### ISSUE THREAD

**Issue by raonadeem** [zdavkeos/whirlyfly#1]
Hi,
I want to import my bit file of Random no Generator to Papilio one 500k.
Can you please guide me how could i generate and load this bit file on board in linux?
I loaded my bit file but it's not working good.
Regards,
Rao nadeem

**Comment by zdavkeos** [comment]
Have you successfully generated the bit file?

Loading the bit stream is pretty easy from there.  The tutorial here is
very good:
http://papilio.cc/index.php?n=Papilio.HighSpeedUART

**Comment by raonadeem** [comment]
Thanks,
I have generated bit file.To load this bit file using (papilio-loader -f whirlyfly.bit)
i have installed papilio loader in ubuntu.But it shows me papilio-prog.I couldn't
load it through ubuntu , So i loaded this bit file from windows XP into board.

To test myy bitstream i run these commands in terminal
but it doesn't shows me anything.

1-) stty --file=/dev/ttyUSB1 speed 3000000

2-) dd bs=1K count=1000 if=/dev/ttyUSB1 of=random_bits.bin

3-) od -t x1 random_bits.bin | head

Tell me please how to load this bit file properly through ubuntu and
If you have a pre-made bitfile kindly mail me that i may confirm 

it.

Regards,
Rao nadeem

**Comment by zdavkeos** [comment]
It sounds like the bitfile loaded ok.

To test on Linux, you have to identify which device it is showing up as. On
my system it is usually /dev/ttyUSB1 (ttyUSB0 is the program loading port
used by the papilio_prog).  Running "dmesg | tail" after plugging in the
papilio will also tell you this i believe.

You can also test if it is sending data by using minicom, putty, gtkterm or
any other graphical terminal program.

I have a few code fixes to commit, and when I do I will add a generated
bitfile to the repository.

**Comment by sanaullah82** [comment]
can you please tell me when you have a plan to load the bitfile in the repository ? or if you can test my bitfile on your board? plz let me know

**Comment by zdavkeos** [comment]
I have added a copy of the bit file that is working for me.

**Comment by sanaullah82** [comment]
thanks......
I will test this and get back to you

**Comment by sanaullah82** [comment]
I have tested you bit file....its working....thanks...
